### ISSUE TITLE
Meta-Issue: Tasks for getting Codemeta better

### ISSUE THREAD

**Issue by ChristianTackeGSI** [FairRootGroup/FairRoot#1351]
(Copied from https://github.com/FairRootGroup/FairRoot/pull/1028#issuecomment-916839687 by @dennisklein)

Individual parts of this list can be handled in dedicated PRs or Issues.

I suggest to follow up on this by:
* [ ] Rebase on current `dev` branch
* [ ] Define the authoritative place for the version number
  a. Keep it in `CMakeLists.txt` or
  b. CMake queries version number from `codemeta.json`
     * Add the [CMake code written by @ChristianTackeGSI](https://github.com/FairRootGroup/FairMQ/pull/324#issuecomment-744620316) that queries the version number from `codemeta.json`
 * [ ] Adopt [`codemeta_update.py`](https://github.com/FairRootGroup/FairMQ/blob/master/codemeta_update.py) from FairMQ repo (in case of b probably can be stripped down to the author logic only)
 * [ ] Add a release checklist for maintainers so we do not forget to press this button from time to time
 * [ ] CI consistency check welcome too 

Regarding the authoritative place for the version number, I personally have no preference whether to go with options a or b. @fuhlig1 @ChristianTackeGSI What is your preference?
